- name: variables
  hosts: 
  vars: #variable declaration
    Course: "Ansible"
    Trainer: "Sivakumer"
    Duration: "120hrs"
  tasks:
    - name: print information
      ansible.builtln.debug:
        msg: "Hi we are learning {{Course}} from trainer {{Trainer}}, Duration is {{Duration}}."