- name: variables
  hosts: localhost
  vars: # variable declaration
    Course: "Terraform"
    Trainer: "Siva"
    Duration: "15hrs"
  tasks:
    - name: print information with overridden variable
      debug: # corrected 'ansible.builtln.debug' to 'debug'
        msg: "Hi we are learning {{ Course }} from trainer {{ Trainer }}, Duration is {{ Duration }}."
      vars: # task level variables 
        Course: "DevOps"

    - name: print information without overridden variable
      debug: # corrected 'ansible.builtln.debug' to 'debug'
        msg: "Hi we are learning {{ Course }} from trainer {{ Trainer }}, Duration is {{ Duration }}."
