- name: variables from files
  hosts: localhost
  vars_files:
    - vars.yaml
  tasks:
    - name: print override information
      debug: # corrected 'ansible.builtln.debug' to 'debug'
        msg: "Hi we are learning {{ Course }} from trainer {{ Trainer }}, Duration is {{ Duration }}."
