- name: variables from arguments
  hosts: localhost
  tasks:
    - name: get from args
      debug:
        msg: "Hi we are learning {{ Course }} from trainer {{ Trainer }}, Duration is {{ Duration }}."