- name: variables preference
  hosts: localhost
  vars:
    WISHES: "Morning from PLAY variable"
  vars_files:
  - vars.yaml
  vars_prompt:
    - name: check preference
      prompt: please enter WISHES
      private: false
  tasks:
    - name: check preference
#      vars:
#       WISHES: "Morning from TASK variable"
      debug:
        msg: "Hello, Good {{WISHES}}"


# 1. arguments
# 2. Task
# 3. 