- name: Conditions
  hosts: web
  become: yes
  tasks:
    - name: check user exists or not
      command: id expense
      ignore_errors: yes

    - name: say Hello
      debug:
        msg: "Hello"
