- name: Conditions
  hosts: web
  become: yes
  tasks:
    - name: check user exists or not
      ansible.builtln.command: id expense
      ignore_errors: true
        
    - name: say Hello
      debug:
        msg: "Hello"
