- name: default value
  hosts: localhost
  tasks:
    - name: print default value
      debug:
        msg: "Hello {{ course | default('Ansible') }}"


- name: upper case
  hosts: localhost
  vars:
    greetings: "Hello, Good Morning"
  tasks:
    - name: convert into uppercase
      debug:
        msg: "{{ greetings | upper }}"


- name: lower case
  hosts: localhost
  vars:
    greetings: "Hello, Good Morning"
  tasks:
    - name: convert into uppercase
      debug:
        msg: "{{ greetings | lower }}"


- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1, 2, 3, 4, 4, 5]
  tasks:
  - name: convert into uppercase
    debug:
      msg: "{{ greetings | unique }}"

- name: print min and max
  hosts: localhost
  vars:
    ages: [25, 35, 67, 89]
  tasks:
  - name: print min and max
    debug:
      msg: "min ages: {{ ages | min }}, max age: {{ ages | max }}"
