- name: install packages
  hosts: web
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.dnf:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: 'mysql', state: 'latest'}   # Install or ensure MySQL is up-to-date
        - { name: 'nginx', state: 'absent'}   # Remove nginx if it's installed
        - { name: 'postfix', state: 'absent'} # Remove postfix if it's installed